"""empty message

Revision ID: 04d6c5a71523
Revises: 6fced6fccac1
Create Date: 2025-05-14 23:12:17.268100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04d6c5a71523'
down_revision = '6fced6fccac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'post', ['Post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Post_id')

    # ### end Alembic commands ###
